name: erlang
base: core18
version: '22.0.7'
summary: Erlang/OTP programming language and build tool Rebar3.
description: |
  Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. Erlang's runtime system has built-in support for concurrency, distribution and fault tolerance.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

parts:
  erlang:
    plugin: autotools
    source-type: tar
    source: https://github.com/erlang/otp/archive/OTP-22.0.7.tar.gz
    build-packages:
      - g++
      - make
      - libssl-dev
      - libncurses-dev
    stage-packages:
      - openssl
      - ncurses-base
    configflags: [ --prefix=/usr ]
    override-build: |
      ./otp_build autoconf
      snapcraftctl build
    stage:
      - usr/lib/erlang/*
      - usr/bin/*
    prime:
      - usr/lib/erlang/*
      - usr/bin/*

  rebar3:
    source: https://github.com/erlang/rebar3/archive/3.13.0.zip
    source-type: zip
    plugin: dump
    override-build: |
      cd rebar3-3.13.0

      cp ../../../../parts/erlang/install/usr/bin/erl ../../../../parts/erlang/install/usr/bin/erl.bk
      cp ../../../../parts/erlang/install/usr/lib/erlang/erts-10.4.4/bin/erl ../../../../parts/erlang/install/usr/lib/erlang/erts-10.4.4/bin/erl.bk

      sed -i '/^ROOTDIR/d' ../../../../parts/erlang/install/usr/bin/erl
      sed -i '/^ROOTDIR/d' ../../../../parts/erlang/install/usr/lib/erlang/erts-10.4.4/bin/erl
      export ROOTDIR=/root/parts/erlang/install/usr/lib/erlang
      export BINDIR=$ROOTDIR/erts-10.4.4/bin
      PATH=../../../../parts/erlang/install/usr/bin/:$PATH ./bootstrap

      mv ../../../../parts/erlang/install/usr/bin/erl.bk ../../../../parts/erlang/install/usr/bin/erl
      mv ../../../../parts/erlang/install/usr/lib/erlang/erts-10.4.4/bin/erl.bk ../../../../parts/erlang/install/usr/lib/erlang/erts-10.4.4/bin/erl

      mkdir -p /root/stage/usr/bin
      mv rebar3 /root/stage/usr/bin
    prime:
      - usr/bin/rebar3

layout:
  /usr/lib/erlang:
    symlink: $SNAP/usr/lib/erlang

apps:
  rebar3:
    command: rebar3
  erl:
    command: erl
  escript:
    command: escript
  ct_run:
    command: ct_run
  dialyzer:
    command: dialyzer
  epmd:
    command: epmd
  erlc:
    command: erlc
  run_erl:
    command: run_erl
  to_erl:
    command: to_erl
  typer:
    command: typer
