name: erlang
base: core18
version: '22.2.2'
summary: Erlang/OTP programming language and build tool Rebar3.
description: |
  Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. Erlang's runtime system has built-in support for concurrency, distribution and fault tolerance.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

parts:
  erlang:
    plugin: autotools
    source-type: tar
    source: https://github.com/erlang/otp/archive/OTP-22.2.2.tar.gz
    build-packages:
      - g++
      - make
      - libssl-dev
      - libncurses-dev
    stage-packages:
      - openssl
      - ncurses-base
    configflags: [ --prefix=/usr ]
    override-build: |
      ./otp_build autoconf
      snapcraftctl build
    prime:
      - usr/lib/erlang/*
      - usr/bin/*

  rebar3-libs:
    source: "https://github.com/erlang/rebar3/releases/download/3.13.0/rebar3"
    # escripts are zip files of the libraries that make them up
    # this will result in a directory of all the rebar3 applications
    source-type: zip
    plugin: dump
    organize:
      '*': usr/lib/rebar3/
    prime:
      - usr/lib/rebar3/*

  rebar3:
    source: snap/local
    plugin: dump
    organize:
      rebar3: usr/bin/rebar3/
    prime:
      - usr/bin/rebar3

layout:
  /usr/lib/erlang:
    symlink: $SNAP/usr/lib/erlang
  /usr/lib/rebar3:
    symlink: $SNAP/usr/lib/rebar3

apps:
  erl:
    command: erl
  rebar3:
    command: rebar3
  escript:
    command: escript
  dialyzer:
    command: dialyzer
  epmd:
    command: epmd
  erlc:
    command: erlc
  typer:
    command: typer

  # uuhhh.. snapcraft won't allow underscores in the names
  run-erl:
    command: run_erl
  to-erl:
    command: to_erl
  ct-run:
    command: ct_run
